CREATE TABLE EMPLOYEE (
 e_id int primary key,
 e_name varchar(30) not null,
 e_email varchar(50) unique,
 e_sal float not null
);

DESC EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(101, "Rahul","r.com",50000);
INSERT INTO EMPLOYEE (e_sal,e_email,e_name,e_id) VALUES(
52000.99, "h.com", "hello",102
);
INSERT INTO EMPLOYEE VALUES(103, "RaJ","ra.com",55000);
INSERT INTO EMPLOYEE VALUES(104, "Rathi","rathi.com",56000);
SELECT * FROM EMPLOYEE;
DELETE FROM EMPLOYEE WHERE e_id= 102;
SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEE SET e_sal= e_sal + 4000 WHERE e_id=101;

SELECT * FROM EMPLOYEE where e_sal >= 55000;
SELECT * FROM EMPLOYEE ORDER BY e_name DESC;
SELECT * FROM EMPLOYEE ORDER BY e_name ASC;
SELECT * FROM EMPLOYEE ORDER  BY e_sal DESC;
SELECT * FROM EMPLOYEE ORDER BY e_sal ASC;
SELECT * FROM EMPLOYEE ORDER BY e_sal DESC LIMIT 3;
SELECT * FROM EMPLOYEE ORDER BY e_sal ASC LIMIT 3;

